#!/bin/bash
#declare -A cor=( [0]="\033[1;37m" [1]="\033[1;34m" [2]="\033[1;31m" [3]="\033[1;33m" [4]="\033[1;32m" )
#SCPfrm="/etc/ger-frm" && [[ ! -d ${SCPfrm} ]] && exit
#SCPinst="/etc/ger-inst" && [[ ! -d ${SCPinst} ]] && exit
dnsnetflix () {
[[ -e /bin/ejecutar/resolv.conf ]] && {
echo "nameserver $dnsp" >> /etc/resolv.conf
#echo "nameserver 8.8.8.8" >> /etc/resolv.conf
msg -bar2
echo -e "${cor[4]}  DNS AGREGADOS CON EXITO"
} || {
cp /etc/resolv.conf /bin/ejecutar/resolv.conf
echo "nameserver $dnsp" >> /etc/resolv.conf
#echo "nameserver $dnsp2" >> /etc/resolv.conf
#echo "nameserver 8.8.8.8" >> /etc/resolv.conf
msg -bar2
echo -e "${cor[4]}  DNS AGREGADOS CON EXITO"
sudo systemctl restart systemd-resolved.service
sudo systemctl restart dnsmasq.service
}
} 
clear
msg -bar2
echo -e "\033[1;93m     AGREGARDOR DE DNS PERSONALES "
msg -bar2
echo -e "\033[1;39m Esta funcion para que puedas ver Netflix con tu VPS"
msg -bar2
echo -e "\033[1;91m ¡ SOLO INGRESA LA IP DEL DNS O SERVIDOR CON SOPORTE"
echo -e "\033[1;39m         Instalara el DNS funcional para Netflix"
#echo -e "\033[1;39m Se deveran agregar en la aplicasion a usar estos DNS."
#echo -e "\033[1;39m En APPS como SS,SSR,V2RAY no es necesario agregarlos."
msg -bar2
echo -e "\033[1;93m Recuerde escojer entre 1 DNS \n       Que sea Valido ."
echo ""
read -p "Ingrese su DNS a usar: " dnsp
echo ""
read -p "Ingrese su 2 DNS a usar: " dnsp2
msg -bar2
read -p " Estas seguro de continuar?  [ s | n ]: " dd   
[[ "$dd" = "s" || "$dd" = "S" ]] && dnsnetflix
msg -bar2
