#! / bin / bash
ve = "\ 033 [1; 32m"; am = "\ 033 [1; 33m"; ver = "\ 033 [1; 31m"; az = "\ 033 [1; 36m"; f = "\ 033 [ 0m "

my_ip () {
MY_IP = $ (ip addr | grep 'inet' | grep -v inet6 | grep -vE '127 \. [0-9] {1,3} \. [0-9] {1,3} \. [0 -9] {1,3} '| grep -o -E' [0-9] {1,3} \. [0-9] {1,3} \. [0-9] {1,3} \. [0-9] {1,3} '| cabeza -1)
MY_IP2 = $ (wget -qO- ipv4.icanhazip.com)
[["$ MEU_IP2"! = "$ MEU_IP2"]] && ip = "$ MEU_IP2" || ip = "$ MY_IP"
}

apt-get install figlet -y> / dev / null 2> & 1
my_ip
echo -e "$ {az}"
figlet ADM.PRO ULTIMATE
echo -e "$ {f}"
dormir 2
echo
echo -e "$ {see} +++++ ATENCIÓN +++++ $ {am}     
TODAS LAS CONTRASEÑAS SIGUIENTE SIEMPRE PONGA EL MISMO $ {f} "
lee -p "¡Ingresa, para continuar!"
apt-get install php5 libapache2-mod-php5 php5-mcrypt -y
apt-get install mysql-server php5-mysql -y
mysql_install_db
echo ""
echo -e "$ {am} Cuando se le solicite $ {view} [S / N] $ {am} elija la opción $ {view} Y $ {am} y $ {ve} OK. $ {am} para todo preguntar
...
$ {am} El siguiente procedimiento de instalación le pedirá una contraseña
luego escribe la contraseña que ingresó antes y la vuelve a confirmar después de presionar $ {ver} Y $ {f} "
lee -p "¡Ingresa, para continuar!"
mysql_secure_installation
echo -e "$ {az} ESPERE LA INSTALACIÓN $ {f}"
dormir 2
apt-get install phpmyadmin -y
php5enmod mcrypt
servicio apache2 reiniciar
echo ""
stty -echo
tput setaf 7; tput negrita; read -p "Ingrese la misma contraseña (Contraseña MySQL):" var7; tput sgr0
echo ""
eco duro; echo
mysql -h localhost -u raíz -p $ var7 -e "CREAR BASE DE DATOS adm"
echo -e "$ {see} ATENCIÓN: INICIAR SESIÓN NO ES PERSONAL $ {f}"
echo ""
echo -e "$ {am} Ahora pongamos un LOGIN y una CONTRASEÑA para acceder a la página de carga de $ {ve}"
	leer -p "Iniciar sesión:" var2
	lee -p "Contraseña:" var3
	echo -ne "$ {f}"

cd / var / www /
   rm -rf index.html> / dev / null 2> & 1
   cp /etc/adm-lite/painel.zip / var / www /
   descomprimir panel.zip> / dev / null 2> & 1
   rm -rf panel.zip> / dev / null 2> & 1
   chmod -R 777 / var / www / adm> / dev / null 2> & 1
sed -i "s; 123; $ var7; g" /var/www/adm/system/seguranca.php> / dev / null 2> & 1

cd / var / www / html /
   rm -rf index.html> / dev / null 2> & 1
   cp /etc/adm-lite/panel.zip / var / www / html /
   descomprimir panel.zip> / dev / null 2> & 1
   rm -rf panel.zip> / dev / null 2> & 1 
   chmod -R 777 / var / www / html / adm> / dev / null 2> & 1
sed -i "s; 123; $ var7; g" /var/www/html/adm/system/seguranca.php> / dev / null 2> & 1

[[! -d / var / www / temp]] && mkdir / var / www / temp
cd / var / www / temp && cp /etc/adm-lite/dados.zip / var / www / temp /
descomprima data.zip> / dev / null 2> & 1

sed -i "s; adm123; $ var2; g" ./bank_data.sql> / dev / null 2> & 1
sed -i "s; adm4321; $ var3; g" ./bank_de_dados.sql> / dev / null 2> & 1

mysql -h localhost -u root -p $ var7 adm <database.sql> / dev / null 2> & 1
rm -rf / var / www / temp

echo -e "$ {am} PANEL DE CARGA EHI INSTALADO PARA INGRESAR A SU ACCESO AL PANEL
$ {az} ---------------------------------------------- ---------------------
$ {view} Url: $ {ve} $ ip: 81 / login.php
$ {am} Inicio de sesión: $ {ve} $ var2
$ {am} Contraseña: $ {ve} $ var3
$ {am} ENLACE PÁGINA PRINCIPAL $ {ve} ($ ip: 81)
$ {az} ---------------------------------------------- --------------------- $ {f} "
echo -e "$ {am}"
lee -p "Presiona ENTER, para continuar" naoa
dormir 2
echo -e "$ {f}"
salir
