#!/bin/bash

#COMPARA
fun_filez () {
arq="/etc/adm-lite/$1"
arq2="$HOME/update/$1"
     [[ ! -e "/etc/adm-lite/$1" ]] && {
     mv -f $arq2 $arq
     return
     }
equal=$(diff -q $arq $arq2)
echo -e "\033[1;31m ${txt[203]}: $1"
     [[ "$equal" = "" ]] && rm $arq2 || {
     mv -f $arq2 $arq
     chmod +x $arq
     lista_atualizados=$(($lista_atualizados + 1))
     echo -e "\033[1;32m ${txt[204]}: $1 - ${txt[205]}!"
     sleep 0.5s
     echo ""
     }
}



#FUNCION VERIFICA

namsobin ()
{
#figlet -p -f slant < /root/name
#echo -e "\033[1;37m      【     ★ ACTUALIZADOR ChumoGH ★     】\033[0m"
#msg -bar #echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
#echo -e "[\033[1;31m-\033[1;33m]\033[1;30m ===☆ Este Apartado es Experimental ☆==\033[1;33m"
#msg -bar #echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
#echo -e "\033[1;37m › IP VPS:\033[0m \033[1;32m 0.0.0.0 \033[1;33m"
unset v keyus
echo -ne " Ingresa tu KEY de INSTALACION : "; read $v
if [ -f /bin/ejecutar/key.fix ];
then
echo "☆Bienvenido a ChumoGH-ADM☆"
 keyus=$(cat /bin/ejecutar/key.fix)
 [[ $keyus = $v ]] && atualiza_fun || exit
fi
}

####

#ATUALIZACAO
atualiza_fun () {
echo -e "${cor[1]} =================================== ${cor[0]}"
cd $HOME
[[ ! -d ./update ]] && mkdir ./update
cd ./update
wget -i $HOME/lista -o /dev/null
for arqs in `ls $HOME/update`; do
fun_filez $arqs
done
  _modulos="/etc/adm-lite/modulos"
  active_verif=$(cat $_modulos | egrep -v "VERIFICAR")
  echo "$active_verif" > $_modulos
  for _pids_ in `atq | awk '{print $1}'`; do
   atrm $_pids_
  done
  [[ -e /etc/adm-lite/vencidos ]] && rm /etc/adm-lite/vencidos
  [[ -e /etc/adm-lite/onlines ]] && rm /etc/adm-lite/onlines
  [[ -e /bin/ejecutar/uskill ]] && ukk=$(cat /bin/ejecutar/uskill) || echo 0 > /bin/ejecutar/uskill 
  [[ -e /root/exito ]] && ex=$(cat /root/exito) || echo  echo "Verified 【 匚 卄 ㄩ 爪 ㄖ Ꮆ 卄 】 ADM 2021" > /root/exito
  [[ -e /root/name ]] && nm=$(cat /root/name) || echo  echo "ChumoGH" > /root/exito
 # rm -f /root/* > /dev/null
 # rm -rf /root/* > /dev/null
  [[ $nm = $nm ]] && echo $nm > /root/name
  [[ $ukk = "" ]] && echo 0 > /bin/ejecutar/uskill
  [[ $ex = "" ]] && echo "Verified 【 匚 卄 ㄩ 爪 ㄖ Ꮆ 卄 】 ADM 2021" > /root/exito
  [[ -e $HOME/lista ]] && rm $HOME/lista
  [[ -d $HOME/update ]] && rm -rf $HOME/update
  [[ "$lista_atualizados" != "" ]] && echo -e "${cor[5]} $lista_atualizados ${txt[206]}"
  [[ -e /etc/adm-lite/idioma ]] && rm /etc/adm-lite/idioma
  echo -e "${cor[1]} =================================== ${cor[0]}"
  cat /root/exito
  echo -e "${cor[1]} =================================== ${cor[0]}"
}

#CORES
cor[1]="\033[1;36m"
cor[2]="\033[1;32m"
cor[3]="\033[1;31m"
cor[4]="\033[1;33m"
cor[0]="\033[1;37m"

#TEXTOS
txt[206]="Archivito(s) Actualizado(s)!"
txt[208]="Invalid Key, Contact the Script Admin!"
txt[207]="Valid!!!"
txt[203]="<>"
txt[204]="㋡--->"
txt[205]="Actualizado"

cd $HOME
[[ -d $HOME/update ]] && rm -rf $HOME/update
[[ -e $HOME/lista ]] && rm $HOME/lista
cd $HOME
 [[ -e /bin/ejecutar/key.fix ]] && echo -e "\033[1;36mTU KEY USADA Fue \033[1;33m$(cat /bin/ejecutar/key.fix)" || echo "ChumoGH2021" > /bin/ejecutar/key.fix
wget -O lista https://raw.githubusercontent.com/ChumoGH/chumogh-gmail.com/master/lista -o /dev/null
atualiza_fun
namsobin
#atualiza_fun
